# Generated by Django 3.2.4 on 2021-06-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_pesanan_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
