# Generated by Django 3.2.4 on 2021-06-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_default_customeraddress_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='status',
            field=models.CharField(choices=[('PRO', 'On Process'), ('PND', 'Pending'), ('COM', 'Complete'), ('CNC', 'Canceled')], default='PND', max_length=15),
        ),
    ]
