# Generated by Django 3.2.4 on 2021-06-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_pesanan_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesanan',
            options={'verbose_name_plural': 'pesanan'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'ShippingAddresses'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
