# Generated by Django 3.2.4 on 2021-06-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210630_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='is_default',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='kabkot',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='kecamatan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='kelurahan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='kode_pos',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='provinsi',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
