CREATE OR REPLACE FUNCTION update_default()
RETURNS trigger AS
$$
	BEGIN
		IF(TG_OP != 'DELETE') THEN
			UPDATE CUSTOMER_ADDRESS SET is_default = FALSE WHERE id != NEW.id;
			RETURN NEW;
		ELSE
			UPDATE CUSTOMER_ADDRESS SET is_default = FALSE;
			RETURN OLD;
		END IF;
	END;
$$
LANGUAGE PLPGSQL;

CREATE TRIGGER set_default_address
AFTER INSERT OR DELETE OR UPDATE OF is_default
ON CUSTOMER_ADDRESS
FOR EACH ROW EXECUTE PROCEDURE update_default();
